### ISSUE TITLE
Error Generating Docs For Modules With @compile {:autoload, false}

### ISSUE THREAD

**Issue by asummers** [elixir-lang/ex_doc#1078]
So we have a module that includes the module attribute:

```elixir
@compile {:autoload, false}
```

The context there is some NIF loading code, if that's important. 

When running `mix docs` it produces the following stack trace:

```
Compiling 1 file (.ex)
** (ExDoc.Retriever.Error) module MyModule is not defined/available
    (ex_doc) lib/ex_doc/retriever.ex:60: ExDoc.Retriever.get_module/2
    (elixir) lib/enum.ex:2994: Enum.flat_map_list/2
    (ex_doc) lib/ex_doc/retriever.ex:43: ExDoc.Retriever.docs_from_modules/2
    (ex_doc) lib/ex_doc.ex:30: ExDoc.generate_docs/3
    (ex_doc) lib/mix/tasks/docs.ex:317: anonymous fn/6 in Mix.Tasks.Docs.run/3
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_doc) lib/mix/tasks/docs.ex:316: Mix.Tasks.Docs.run/3
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
```

This module has `@moduledoc false` and `@doc false` above all the functions, so I'm not sure if there's something I can do to tell it to not try to do this. When removing the autoload false, it succeeds normally.

**Comment by asummers** [comment]
Can confirm this is now fixed after `24d9783`. Thanks @josevalim
