### ISSUE TITLE
ex_doc 0.22 causes an exception in earmark 1.4.4

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/ex_doc#1172]
In my [ex_cldr_units](https://github.com/elixir-cldr/cldr_units) lib, `ex_doc` 0.22.0 raise the following error in `earmark`. I'm raising the issue here because whether on `ex_doc` 0.20, 0.21 or 0.22 the version of `earmark` is `1.4.4` so I assume the error is caused by a regression in `ex_doc`.

The exception occurs on Elixir 1.10.3 and master with at least OTP 23.
There is no exception with `ex_doc` 0.20 or 0.21.

```bash
Generated ex_cldr_units app
Generating docs...
** (FunctionClauseError) no function clause matching in Earmark.Helpers.AstHelpers.augment_tag_with_ial/2    
    
    The following arguments were given to Earmark.Helpers.AstHelpers.augment_tag_with_ial/2:
    
        # 1
        []
    
        # 2
        %{}
    
    Attempted function clauses (showing 1 out of 1):
    
        def augment_tag_with_ial([{t, a, c} | tags], atts)
    
    (earmark 1.4.4) lib/earmark/helpers/ast_helpers.ex:12: Earmark.Helpers.AstHelpers.augment_tag_with_ial/2
    (earmark 1.4.4) lib/earmark/ast/inline.ex:214: Earmark.Ast.Inline.converter_for_inline_ial/1
    (elixir 1.10.3) lib/enum.ex:3333: Enum.find_value_list/3
    (earmark 1.4.4) lib/earmark/ast/inline.ex:24: Earmark.Ast.Inline._convert/4
    (earmark 1.4.4) lib/earmark/ast_renderer.ex:33: Earmark.AstRenderer.render_block/2
    (earmark 1.4.4) lib/earmark/ast_renderer.ex:24: Earmark.AstRenderer._render/3
    (earmark 1.4.4) lib/earmark/ast_renderer.ex:16: Earmark.AstRenderer.render/2
    (earmark 1.4.4) lib/earmark/ast_renderer.ex:156: Earmark.AstRenderer.render_block/2
```

**Comment by wojtekmach** [comment]
Thank you for the report. I was able to narrow it down to Earmark:

```
iex> text = "Adds two compatible `%Unit{}` types\n\n## Options\n\n* `unit_1` and `unit_2` are compatible Units\n  returned by `Cldr.Unit.new/2`\n\n## Returns\n\n* A `%Unit{}` of the same type as `unit_1` with a value\n  that is the sum of `unit_1` and the potentially converted\n  `unit_2` or\n\n* {:error, {IncompatibleUnitError, message}}\n\n## Examples\n\n    iex> Cldr.Unit.Math.add Cldr.Unit.new!(:foot, 1), Cldr.Unit.new!(:foot, 1)\n    #Cldr.Unit<:foot, 2>\n\n    iex> Cldr.Unit.Math.add Cldr.Unit.new!(:foot, 1), Cldr.Unit.new!(:mile, 1)\n    #Cldr.Unit<:foot, 5281>\n\n    iex> Cldr.Unit.Math.add Cldr.Unit.new!(:foot, 1), Cldr.Unit.new!(:gallon, 1)\n    {:error, {Cldr.Unit.IncompatibleUnitsError,\n      \"Operations can only be performed between units of the same category. Received #Cldr.Unit<:foot, 1> and #Cldr.Unit<:gallon, 1>\"}}\n\n"
iex> Earmark.as_ast(text)
** (FunctionClauseError) no function clause matching in Earmark.Helpers.AstHelpers.augment_tag_with_ial/2

    The following arguments were given to Earmark.Helpers.AstHelpers.augment_tag_with_ial/2:

        # 1
        []

        # 2
        %{}

    Attempted function clauses (showing 1 out of 1):

        def augment_tag_with_ial([{t, a, c} | tags], atts)

    (earmark 1.4.4) lib/earmark/helpers/ast_helpers.ex:12: Earmark.Helpers.AstHelpers.augment_tag_with_ial/2
    (earmark 1.4.4) lib/earmark/ast/inline.ex:214: Earmark.Ast.Inline.converter_for_inline_ial/1
    (elixir 1.10.2) lib/enum.ex:3333: Enum.find_value_list/3
    (earmark 1.4.4) lib/earmark/ast/inline.ex:24: Earmark.Ast.Inline._convert/4
    (earmark 1.4.4) lib/earmark/ast_renderer.ex:153: Earmark.AstRenderer.render_block/3
    (earmark 1.4.4) lib/earmark/ast_renderer.ex:25: Earmark.AstRenderer._render/3
    (earmark 1.4.4) lib/earmark/ast_renderer.ex:143: Earmark.AstRenderer.render_block/3
    (earmark 1.4.4) lib/earmark/ast_renderer.ex:25: Earmark.AstRenderer._render/3
```

Narrowing it down further:

```elixir
text = "* {:error, {IncompatibleUnitError, message}}"
Earmark.as_ast(text)
```

I can reproduce it too.

Changing it to the following fixes it: (note backtics)

```elixir
text = "* `{:error, {IncompatibleUnitError, message}}`"
Earmark.as_ast(text)
```

so that's what I'd do in the meantime. I'll report it to Earmark.

**Comment by kipcole9** [comment]
Thanks @wojtekmach - No idea how you do that. Take an exception and find the cause so quickly! Much appreciated.

**Comment by wojtekmach** [comment]
printf-based debugging ftw :D
