### ISSUE TITLE
Error could not write to file

### ISSUE THREAD

**Issue by maennchen** [elixir-lang/ex_doc#1344]
## Steps to reproduce

Add the following modules:

<details>
<summary>
<code>hygeia_xml.ex</code>

</summary>

```elixir
defmodule HygeiaXml do
  @moduledoc """
  Hygeia XML Schema Helper
  """

  defmacro __using__(opts) do
    quote bind_quoted: [opts: opts] do
      require Record

      path = Keyword.fetch!(opts, :path)

      hrl_path =
        path
        |> Path.dirname()
        |> Path.join(Path.basename(path, ".xsd") <> ".hrl")

      model =
        path
        |> File.read!()
        |> :erlsom.compile()
        |> case do
          {:ok, model} -> model
        end

      :erlsom.write_hrl(model, hrl_path)

      @external_resource path

      for {name, def} <- Record.extract_all(from: hrl_path) do
        firendly_name =
          name
          |> Atom.to_string()
          |> String.replace_leading("p:", "")
          |> String.to_atom()

        Record.defrecord(firendly_name, name, def)
      end

      @spec model :: term()
      def model, do: unquote(Macro.escape(model))

      @spec write(data :: term) :: {:ok, content :: binary()} | {:error, term()}
      def write(data), do: :erlsom.write(data, unquote(Macro.escape(model)), output: :binary)

      @spec read(content :: String.t()) ::
              {:ok, structure :: term(), trailing_characters :: binary()} | {:error, term()}
      def read(content), do: :erlsom.scan(content, unquote(Macro.escape(model)))
    end
  end
end
```
</details>

<details>
<summary>
<code>sedex/schema.ex</code>

</summary>

```elixir
defmodule Sedex.Schema do
  @moduledoc false

  schema_paths =
    :sedex
    |> Application.app_dir("priv/schema/")
    |> Kernel.<>("/*.xsd")
    |> Path.wildcard()

  for path <- schema_paths do
    @external_resource path

    name =
      path
      |> Path.basename(".xsd")
      |> String.replace("-", "_")
      |> Macro.camelize()
      |> String.to_atom()

    # credo:disable-for-next-line Credo.Check.Warning.UnsafeToAtom
    defmodule Module.concat(__MODULE__, name) do
      @moduledoc """
      #{name} schema
      """

      use HygeiaXml, path: path
    end
  end
end
```
</details>

Based on the following XSD: https://github.com/republique-et-canton-de-geneve/sedex-Message-Handler/blob/master/src/main/java/ch/admin/suis/msghandler/xml/v2/eCH-0090-2-0.xsd

## Output

<details>
<summary>
<code>$ mix docs</code>
</summary>

```
==> hygeia
Compiling 24 files (.ex)
==> hygeia_pdf_confirmation
Compiling 1 file (.ex)
==> hygeia_user_sync
Compiling 1 file (.ex)
==> hygeia_web
Compiling 97 files (.ex)
Generating docs...
warning: documentation references module "Cldr.Calendar.Gregorian" but it is hidden
  apps/hygeia_cldr/lib/hygeia_cldr.ex:1: HygeiaCldr.calendar_from_territory/1

warning: documentation references module "Cldr.Calendar.Gregorian" but it is hidden
  apps/hygeia_cldr/lib/hygeia_cldr.ex:1: HygeiaCldr.calendar_from_territory/1

warning: documentation references module "Cldr.Rfc5646.Parser" but it is hidden
  apps/hygeia_cldr/lib/hygeia_cldr.ex:1: HygeiaCldr.put_locale/1

warning: documentation references module "Cldr.Rfc5646.Parser" but it is hidden
  apps/hygeia_cldr/lib/hygeia_cldr.ex:1: HygeiaCldr.validate_locale/1

warning: documentation references "Cldr.Number.PluralRule.plural_type()" but it is hidden or private
  apps/hygeia_cldr/lib/hygeia_cldr.ex:1: HygeiaCldr.Number.Cardinal.plural_rule/3

warning: documentation references "Cldr.Number.PluralRule.plural_type()" but it is hidden or private
  apps/hygeia_cldr/lib/hygeia_cldr.ex:1: HygeiaCldr.Number.Ordinal.plural_rule/3

warning: documentation references "Cldr.Number.PluralRule.plural_type()" but it is hidden or private
  apps/hygeia_cldr/lib/hygeia_cldr.ex:1: HygeiaCldr.Number.PluralRule.Range.plural_rule/3

warning: documentation references "Cldr.Number.PluralRule.plural_type()" but it is hidden or private
  apps/hygeia_cldr/lib/hygeia_cldr.ex:1: HygeiaCldr.Number.PluralRule.Range.plural_rule/3

warning: documentation references "Cldr.Number.PluralRule.plural_type()" but it is hidden or private
  apps/hygeia_cldr/lib/hygeia_cldr.ex:1: HygeiaCldr.Number.PluralRule.Range.plural_rule/3


14:59:12.436 [error] Task #PID<0.13203.0> started from #PID<0.95.0> terminating
** (File.Error) could not write to file "/home/maennchen/Development/hygeia/backend/doc/Sedex.Schema.ECH009010-macro-envelopeType/loopback.html": no such file or directory
    (elixir 1.11.3) lib/file.ex:1053: File.write!/3
    (elixir 1.11.3) lib/enum.ex:804: anonymous fn/3 in Enum.each/2
    (stdlib 3.14) maps.erl:233: :maps.fold_1/3
    (elixir 1.11.3) lib/enum.ex:2209: Enum.each/2
    (ex_doc 0.24.0) lib/ex_doc/formatter/html.ex:468: ExDoc.Formatter.HTML.generate_module_page/3
    (elixir 1.11.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<9.27504876/1 in ExDoc.Formatter.HTML.generate_list/3>, [%ExDoc.ModuleNode{deprecated: nil, doc: [{:p, [], ["ECH009010 schema"], %{}}], doc_line: 22, docs: [%ExDoc.FunctionNode{annotations: ["macro"], arity: 1, defaults: [envelopeType: 0], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "envelopeType/1", name: :envelopeType, rendered_doc: nil, signature: "envelopeType(args \\\\ [])", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 2, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "envelopeType/2", name: :envelopeType, rendered_doc: nil, signature: "envelopeType(record, args)", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 1, defaults: ["envelopeType/loopback": 0], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "envelopeType/loopback/1", name: :"envelopeType/loopback", rendered_doc: nil, signature: "envelopeType/loopback(args \\\\ [])", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 2, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "envelopeType/loopback/2", name: :"envelopeType/loopback", rendered_doc: nil, signature: "envelopeType/loopback(record, args)", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: [], arity: 0, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "model/0", name: :model, rendered_doc: nil, signature: "model()", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: ["model() :: <a href=\"https://hexdocs.pm/elixir/typespecs.html#built-in-types\">term</a>()"], type: :function}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 1, defaults: [nameValuePairType: 0], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "nameValuePairType/1", name: :nameValuePairType, rendered_doc: nil, signature: "nameValuePairType(args \\\\ [])", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 2, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "nameValuePairType/2", name: :nameValuePairType, rendered_doc: nil, signature: "nameValuePairType(record, args)", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 1, defaults: [qname: 0], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "qname/1", name: :qname, rendered_doc: nil, signature: "qname(args \\\\ [])", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 2, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "qname/2", name: :qname, rendered_doc: nil, signature: "qname(record, args)", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: [], arity: 1, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "read/1", name: :read, rendered_doc: nil, signature: "read(content)", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: ["read(content :: <a href=\"https://hexdocs.pm/elixir/String.html#t:t/0\">String.t</a>()) ::\n  {:ok, structure :: <a href=\"https://hexdocs.pm/elixir/typespecs.html#built-in-types\">term</a>(), trailing_characters :: <a href=\"https://hexdocs.pm/elixir/typespecs.html#built-in-types\">binary</a>()} | {:error, <a href=\"https://hexdocs.pm/elixir/typespecs.html#built-in-types\">term</a>()}"], type: :function}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 1, defaults: [receiptType: 0], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "receiptType/1", name: :receiptType, rendered_doc: nil, signature: "receiptType(args \\\\ [])", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 2, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "receiptType/2", name: :receiptType, rendered_doc: nil, signature: "receiptType(record, args)", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: [], arity: 1, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "write/1", name: :write, rendered_doc: nil, signature: "write(data)", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: ["write(data :: <a href=\"https://hexdocs.pm/elixir/typespecs.html#built-in-types\">term</a>()) :: {:ok, content :: <a href=\"https://hexdocs.pm/elixir/typespecs.html#built-in-types\">binary</a>()} | {:error, <a href=\"https://hexdocs.pm/elixir/typespecs.html#built-in-types\">term</a>()}"], type: :function}], function_groups: ["Functions"], group: nil, id: "Sedex.Schema.ECH009010", module: Sedex.Schema.ECH009010, nested_context: nil, nested_title: nil, rendered_doc: "<p>ECH009010 schema</p>", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, title: "Sedex.Schema.ECH009010", type: :module, typespecs: []}]]

14:59:12.434 [error] Task #PID<0.13205.0> started from #PID<0.95.0> terminating
** (File.Error) could not write to file "/home/maennchen/Development/hygeia/backend/doc/Sedex.Schema.ECH009020-macro-envelopeType/loopback.html": no such file or directory
    (elixir 1.11.3) lib/file.ex:1053: File.write!/3
    (elixir 1.11.3) lib/enum.ex:804: anonymous fn/3 in Enum.each/2
    (stdlib 3.14) maps.erl:233: :maps.fold_1/3
    (elixir 1.11.3) lib/enum.ex:2209: Enum.each/2
    (ex_doc 0.24.0) lib/ex_doc/formatter/html.ex:468: ExDoc.Formatter.HTML.generate_module_page/3
    (elixir 1.11.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<9.27504876/1 in ExDoc.Formatter.HTML.generate_list/3>, [%ExDoc.ModuleNode{deprecated: nil, doc: [{:p, [], ["ECH009020 schema"], %{}}], doc_line: 22, docs: [%ExDoc.FunctionNode{annotations: ["macro"], arity: 1, defaults: [envelopeType: 0], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "envelopeType/1", name: :envelopeType, rendered_doc: nil, signature: "envelopeType(args \\\\ [])", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 2, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "envelopeType/2", name: :envelopeType, rendered_doc: nil, signature: "envelopeType(record, args)", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 1, defaults: ["envelopeType/loopback": 0], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "envelopeType/loopback/1", name: :"envelopeType/loopback", rendered_doc: nil, signature: "envelopeType/loopback(args \\\\ [])", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 2, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "envelopeType/loopback/2", name: :"envelopeType/loopback", rendered_doc: nil, signature: "envelopeType/loopback(record, args)", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: [], arity: 0, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "model/0", name: :model, rendered_doc: nil, signature: "model()", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: ["model() :: <a href=\"https://hexdocs.pm/elixir/typespecs.html#built-in-types\">term</a>()"], type: :function}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 1, defaults: [nameValuePairType: 0], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "nameValuePairType/1", name: :nameValuePairType, rendered_doc: nil, signature: "nameValuePairType(args \\\\ [])", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 2, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "nameValuePairType/2", name: :nameValuePairType, rendered_doc: nil, signature: "nameValuePairType(record, args)", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 1, defaults: [qname: 0], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "qname/1", name: :qname, rendered_doc: nil, signature: "qname(args \\\\ [])", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 2, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "qname/2", name: :qname, rendered_doc: nil, signature: "qname(record, args)", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: [], arity: 1, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "read/1", name: :read, rendered_doc: nil, signature: "read(content)", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: ["read(content :: <a href=\"https://hexdocs.pm/elixir/String.html#t:t/0\">String.t</a>()) ::\n  {:ok, structure :: <a href=\"https://hexdocs.pm/elixir/typespecs.html#built-in-types\">term</a>(), trailing_characters :: <a href=\"https://hexdocs.pm/elixir/typespecs.html#built-in-types\">binary</a>()} | {:error, <a href=\"https://hexdocs.pm/elixir/typespecs.html#built-in-types\">term</a>()}"], type: :function}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 1, defaults: [receiptType: 0], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "receiptType/1", name: :receiptType, rendered_doc: nil, signature: "receiptType(args \\\\ [])", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: ["macro"], arity: 2, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "receiptType/2", name: :receiptType, rendered_doc: nil, signature: "receiptType(record, args)", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: [], type: :macro}, %ExDoc.FunctionNode{annotations: [], arity: 1, defaults: [], deprecated: nil, doc: nil, doc_line: 26, group: "Functions", id: "write/1", name: :write, rendered_doc: nil, signature: "write(data)", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, specs: ["write(data :: <a href=\"https://hexdocs.pm/elixir/typespecs.html#built-in-types\">term</a>()) :: {:ok, content :: <a href=\"https://hexdocs.pm/elixir/typespecs.html#built-in-types\">binary</a>()} | {:error, <a href=\"https://hexdocs.pm/elixir/typespecs.html#built-in-types\">term</a>()}"], type: :function}], function_groups: ["Functions"], group: nil, id: "Sedex.Schema.ECH009020", module: Sedex.Schema.ECH009020, nested_context: nil, nested_title: nil, rendered_doc: "<p>ECH009020 schema</p>", source_path: "apps/sedex/lib/sedex/schema.ex", source_url: nil, title: "Sedex.Schema.ECH009020", type: :module, typespecs: []}]]
** (EXIT from #PID<0.95.0>) an exception was raised:
    ** (File.Error) could not write to file "/home/maennchen/Development/hygeia/backend/doc/Sedex.Schema.ECH009020-macro-envelopeType/loopback.html": no such file or directory
        (elixir 1.11.3) lib/file.ex:1053: File.write!/3
        (elixir 1.11.3) lib/enum.ex:804: anonymous fn/3 in Enum.each/2
        (stdlib 3.14) maps.erl:233: :maps.fold_1/3
        (elixir 1.11.3) lib/enum.ex:2209: Enum.each/2
        (ex_doc 0.24.0) lib/ex_doc/formatter/html.ex:468: ExDoc.Formatter.HTML.generate_module_page/3
        (elixir 1.11.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
        (elixir 1.11.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
        (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

</details>

## Affected Versions

`0.24.0`

**Comment by wojtekmach** [comment]
Thank you for the report, could you try latest master? If this works, we'll cut a new release soon.

**Comment by maennchen** [comment]
@wojtekmach I'll trylmaster on monday, thanks for the fast fix ❤️

**Comment by maennchen** [comment]
@wojtekmach The newest release works

**Comment by wojtekmach** [comment]
Great, thanks!
