### ISSUE TITLE
Error generating docs

### ISSUE THREAD

**Issue by Kartstig** [elixir-lang/ex_doc#1363]
Elixir: 1.11.2
OTP 22
erts-10.6.4

I got the following error:
```
Publishing package to public repository hexpm.

Proceed? [Yn] 
Building docs...
** (ArgumentError) expected a keyword list, but an entry in the list is not a two-element tuple with an atom as its first element, got: {{:terminate, 2}, [{:type, 646, :bounded_fun, [{:type, 646, :fun, [{:type, 646, :product, [{:var, 646, :reason}, {:ann_type, 646, [{:var, 646, :state}, {:type, 646, :term, []}]}]}, {:type, 646, :term, []}]}, [{:type, 646, :constraint, [{:atom, 646, :is_subtype}, [{:var, 646, :reason}, {:type, 647, :union, [{:atom, 0, :normal}, {:atom, 0, :shutdown}, {:type, 0, :tuple, [{:atom, 0, :shutdown}, {:type, 647, :term, []}]}, {:type, 647, :term, []}]}]]}]]}]}
    (elixir 1.11.2) lib/keyword.ex:475: Keyword.keys/1
    (ex_doc 0.21.3) lib/ex_doc/retriever.ex:374: anonymous fn/2 in ExDoc.Retriever.get_impls/1
    (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_doc 0.21.3) lib/ex_doc/retriever.ex:373: ExDoc.Retriever.get_impls/1
    (ex_doc 0.21.3) lib/ex_doc/retriever.ex:164: ExDoc.Retriever.get_module_data/2
    (ex_doc 0.21.3) lib/ex_doc/retriever.ex:115: ExDoc.Retriever.generate_node/3
    (elixir 1.11.2) lib/enum.ex:3421: Enum.flat_map_list/2
    (elixir 1.11.2) lib/enum.ex:3422: Enum.flat_map_list/2
```

so I upgraded ex_doc to 0.24.2

and now I get this error:
```
Publishing package to public repository hexpm.

Proceed? [Yn] 
Building docs...
** (MatchError) no match of right hand side value: {:error, {:earmark, {'no such file or directory', 'earmark.app'}}}
    (ex_doc 0.21.3) lib/mix/tasks/docs.ex:302: Mix.Tasks.Docs.run/3
    (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
    (hex 0.21.1) lib/mix/tasks/hex.publish.ex:225: Mix.Tasks.Hex.Publish.docs_task/0
    (hex 0.21.1) lib/mix/tasks/hex.publish.ex:187: Mix.Tasks.Hex.Publish.create/3
    (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.2) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

**Comment by josevalim** [comment]
The second one should be fixed by running the command again or removing _build. It is a bug we had when upgrading ExDoc versions. Can you please try again?

**Comment by Kartstig** [comment]
That did the trick!

It's been a while, and I probably should have known to run a `mix clean`

I really appreciate the quick response. Now get back to doing cooler things :)
