### ISSUE TITLE
Unclear error messages

### ISSUE THREAD

**Issue by mathieuprog** [elixir-lang/ex_doc#1397]
As I try to publish a new version of a library, I got the following error:

> Building docs...
> ** (ArgumentError) expected a keyword list, but an entry in the list is not a two-element tuple with an atom as its first element, got: {{:to_query, 1}, [{:type, 9, :fun, [{:type, 9, :product, [{:user_type, 9, :t, []}]}, {:type, 9, :term, []}]}]}
> (elixir 1.12.3) lib/keyword.ex:475: Keyword.keys/1
> (ex_doc 0.21.2) lib/ex_doc/retriever.ex:385: anonymous fn/2 in ExDoc.Retriever.get_impls/1
> (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
> (ex_doc 0.21.2) lib/ex_doc/retriever.ex:384: ExDoc.Retriever.get_impls/1
> (ex_doc 0.21.2) lib/ex_doc/retriever.ex:164: ExDoc.Retriever.get_module_data/2
> (ex_doc 0.21.2) lib/ex_doc/retriever.ex:115: ExDoc.Retriever.generate_node/3
> (elixir 1.12.3) lib/enum.ex:3900: Enum.flat_map_list/2
> (ex_doc 0.21.2) lib/ex_doc/retriever.ex:43: ExDoc.Retriever.docs_from_modules/2

But as I had no information as to where is an error, I first just tried to update `ex_doc` from 0.21 to 0.25 in the hope it would be more clear, but now I got the following error:

> Building docs...
> ** (MatchError) no match of right hand side value: {:error, {:earmark, {'no such file or directory', 'earmark.app'}}}
>    (ex_doc 0.21.2) lib/mix/tasks/docs.ex:302: Mix.Tasks.Docs.run/3
>    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
>    (hex 0.21.2) lib/mix/tasks/hex.publish.ex:225: Mix.Tasks.Hex.Publish.docs_task/0
>    (hex 0.21.2) lib/mix/tasks/hex.publish.ex:187: Mix.Tasks.Hex.Publish.create/3
>    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
>    (mix 1.12.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2

Anyone knows what's happening?

**Comment by mathieuprog** [comment]
Deleted deps, re-fetched deps and recompiled, now it works.
