### ISSUE TITLE
About displaying images available in a project

### ISSUE THREAD

**Issue by patatoid** [elixir-lang/ex_doc#1568]
Hi,

Thanks for the great work done on ex_doc, one of the best documentation tools I ever worked with.

I have incorporated an image in the README of one of my projects, those are displayed in GitHub or GitLab providing the relative path to it. Is there any way to have the same behavior with ex_doc?

Adding the image to the extras in mix.exs configuration raises an error while compiling the docs:

```
Generating docs...

20:46:21.417 [error] Task #PID<0.998.0> started from #PID<0.94.0> terminating
** (ArgumentError) file extension not recognized, allowed extension is either .md, .txt or no extension
    (ex_doc 0.28.0) lib/ex_doc/formatter/html.ex:368: ExDoc.Formatter.HTML.build_extra/6
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.86504095/1 in ExDoc.Formatter.HTML.build_extras/2>, ["images/oid-certification-mark.png"]]
** (EXIT from #PID<0.94.0>) an exception was raised:
    ** (ArgumentError) file extension not recognized, allowed extension is either .md, .txt or no extension
        (ex_doc 0.28.0) lib/ex_doc/formatter/html.ex:368: ExDoc.Formatter.HTML.build_extra/6
        (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
        (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
        (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

If any further work is needed, I would be happy to contribute (with some guidance) if the feature is considered useful.

Thanks once more,
Cheers

**Comment by josevalim** [comment]
Please check the :assets configuration in the docs: https://hexdocs.pm/ex_doc/Mix.Tasks.Docs.html
