### ISSUE TITLE
** (MatchError) no match of right hand side value: {:error, {:earmark, {'no such file or directory', 'earmark.app'}}}

### ISSUE THREAD

**Issue by thojanssens** [elixir-lang/ex_doc#1743]
I have the following error when running
> mix hex.publish

> Publishing package to public repository hexpm.

> Proceed? [Yn] Y
> Building docs...
> ** (MatchError) no match of right hand side value: {:error, {:earmark, {'no such file or directory', 'earmark.app'}}}
    (ex_doc 0.21.2) lib/mix/tasks/docs.ex:302: Mix.Tasks.Docs.run/3
    (mix 1.14.4) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (hex 2.0.6) lib/mix/tasks/hex.publish.ex:191: Mix.Tasks.Hex.Publish.docs_task/0
    (hex 2.0.6) lib/mix/tasks/hex.publish.ex:146: Mix.Tasks.Hex.Publish.create/3
    (mix 1.14.4) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.4) lib/mix/cli.ex:84: Mix.CLI.run_task/2

I don't see any requirement regarding `earmark` in the docs. What am I missing?

As dependency I added
```elixir
{:ex_doc, "~> 0.30", only: :dev, runtime: false}
```

**Comment by thojanssens** [comment]
Had to delete `_build` folder.

Can't we try to rescue this error and suggest devs to delete their `_build` folder, until this error is properly addressed?
