### ISSUE TITLE
Protocol Undefined Error after upgrading from 0.30.6 to 0.30.7

### ISSUE THREAD

**Issue by SteffenDE** [elixir-lang/ex_doc#1792]
After upgrading from from 0.30.6 to 0.30.7 I get the following error when running `mix docs`:

```elixir
** (Protocol.UndefinedError) protocol Enumerable not implemented for {[%ExDoc.ModuleNode{id ... %ExDoc.ModuleNode{...}, ...], []} of type Tuple. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, Phoenix.LiveView.LiveStream, Postgrex.Stream, Range, Stream, Timex.Interval
    (elixir 1.15.5) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.15.5) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.15.5) lib/enum.ex:4387: Enum.reverse/1
    (elixir 1.15.5) lib/enum.ex:3704: Enum.to_list/1
    (elixir 1.15.5) lib/enum.ex:4319: Enum.flat_map_list/2
    (ex_doc 0.30.7) lib/ex_doc/retriever.ex:30: ExDoc.Retriever.docs_from_dir/2
    (ex_doc 0.30.7) lib/ex_doc.ex:24: ExDoc.generate_docs/3
    (ex_doc 0.30.7) lib/mix/tasks/docs.ex:387: anonymous fn/6 in Mix.Tasks.Docs.run/3
```

I cannot share the full error message, as it contains nearly our full internal documentation.

The ExDoc config looks like this:

```elixir
defp docs do
    [
      # The main page in the docs
      main: "overview",
      extras:
        Path.wildcard("../documentation/architecture/*.livemd") ++
          Path.wildcard("../documentation/getting-started/*.livemd") ++
          [
            "README.md": [filename: "overview", title: "Overview"]
          ],
      groups_for_extras: [
        "Getting started": Path.wildcard("../documentation/getting-started/**/*.livemd"),
        Architecture: Path.wildcard("../documentation/architecture/**/*.livemd")
      ],
      groups_for_functions: [
        Components: &(&1[:type] == :component)
      ],
      groups_for_modules: docs_groups_for_modules(),
      source_url_pattern: "...",
      before_closing_body_tag: &docs_before_closing_body_tag/1
    ]
  end

  defp docs_groups_for_modules do
    [
      "UI Components": [
        MyComponts.Button,
        ...
      ]
    ]
  end

  defp docs_before_closing_body_tag(:html) do
    # https://hexdocs.pm/ex_doc/readme.html#extensions
    """
    <script src="https://cdn.jsdelivr.net/npm/mermaid@9.0.1/dist/mermaid.min.js"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function () {
        mermaid.initialize({ startOnLoad: false });
        let id = 0;
        for (const codeEl of document.querySelectorAll("pre code.mermaid")) {
          const preEl = codeEl.parentElement;
          const graphDefinition = codeEl.textContent;
          const graphEl = document.createElement("div");
          const graphId = "mermaid-graph-" + id++;
          mermaid.render(graphId, graphDefinition, function (svgSource, bindListeners) {
            graphEl.innerHTML = svgSource;
            bindListeners && bindListeners(graphEl);
            preEl.insertAdjacentElement("afterend", graphEl);
            preEl.remove();
          });
        }
      });
    </script>
    """
  end

  defp docs_before_closing_body_tag(_), do: ""
```

It's an umbrella project if that matters. I think this error was introduced by 960e2ef.

**Comment by SteffenDE** [comment]
Works on main, thank you!

**Comment by josevalim** [comment]
Released!
