### ISSUE TITLE
Mix Docs Build faill

### ISSUE THREAD

**Issue by DesmondLouis** [elixir-lang/ex_doc#1797]
Proceed? [Yn] 
Building docs...

12:25:45.799 [notice] Application makeup exited: exited in: Makeup.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Makeup.Application.start/2 is undefined (module Makeup.Application is not available)
            (makeup 1.1.0) Makeup.Application.start(:normal, [])
            (kernel 9.0.2) application_master.erl:293: :application_master.start_it_old/4

12:25:45.806 [notice] Application nimble_parsec exited: :stopped

12:25:45.806 [notice] Application earmark_parser exited: :stopped

12:25:45.806 [notice] Application eex exited: :stopped
** (MatchError) no match of right hand side value: {:error, {:makeup, {:bad_return, {{Makeup.Application, :start, [:normal, []]}, {:EXIT, {:undef, [{Makeup.Application, :start, [:normal, []], []}, {:application_master, :start_it_old, 4, [file: ~c"application_master.erl", line: 293]}]}}}}}}
    (ex_doc 0.30.9) lib/mix/tasks/docs.ex:337: Mix.Tasks.Docs.run/3
    (mix 1.15.7) lib/mix/task.ex:455: anonymous fn/3 in Mix.Task.run_task/5
    (hex 2.0.6) lib/mix/tasks/hex.publish.ex:191: Mix.Tasks.Hex.Publish.docs_task/0
    (hex 2.0.6) lib/mix/tasks/hex.publish.ex:146: Mix.Tasks.Hex.Publish.create/3
    (mix 1.15.7) lib/mix/task.ex:455: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.7) lib/mix/cli.ex:92: Mix.CLI.run_task/2
    /Users/noutcha/.asdf/installs/elixir/1.15.7/bin/mix:2: (file)

**Comment by josevalim** [comment]
Can you please provide an application that reproduces the error? And can you provide your `mix.exs`?

**Comment by DesmondLouis** [comment]
Hello @josevalim 
```elixir
defmodule DemoApp.MixProject do
  use Mix.Project

  def project do
    [
      app: :demo_app,
      version: "0.2.2",
      elixir: "~> 1.14",
      start_permanent: Mix.env() == :prod,
      deps: deps(),
      description: description(),
      package: package(),
      deps: deps(),
      name: "Firebase Elixir API Library",
      source_url: "https://github.com/xx/demo_app",
      docs: [
        main: "Demo Elixir API Library",
        #        logo: "",
        extras: ["README.md"]
      ]
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger],
      mod: {DemoApp.Application, []},
      applications: [:jose]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      {:joken, "~> 2.6"},
      {:jose, "~> 1.11"},
      {:plug, "~> 1.15"},
      {:plug_cowboy, "~> 2.0"},
      {:ex_firebase_auth, "~> 0.5.1"},
      {:ex_doc, ">= 0.0.0", runtime: false},
      {:credo, "~> 1.7", only: [:dev, :test], runtime: false},
      {:versioce, "~> 0.2.1"}
    ]
  end

  defp description() do
    "xx firebase authentication library."
  end

  defp package() do
    [
      # This option is only needed when you don't want to use the OTP application name
      name: "demo_app",
      organization: "xx",
      # These are the default files included in the package
      files: ~w(lib .formatter.exs mix.exs README*),
      licenses: ["Proprietary"],
      links: %{"GitHub" => "https://github.com/xx/demo_app"}
    ]
  end
end


```

**Comment by DesmondLouis** [comment]
@josevalim That doesn't seem to be the root cause of the issue. I have removed `applications: [:jose]` from my mix.exs file deleted the _build folder and compiled the project, but when i run `mix docs` I get the same error log

**Comment by josevalim** [comment]
I see, so can you please provide an application that reproduces the error?

**Comment by DesmondLouis** [comment]
actually for context I am building a library aimed at authenticate users with firebase tokens

**Comment by josevalim** [comment]
If it is public, then I can take a look. Otherwise a mix.exs to reproduce it is necessary.

**Comment by DesmondLouis** [comment]
It is a private remix of the mix.The example I sent earlier is the actual mix.examples of the project

**Comment by josevalim** [comment]
The `mix.exs` file fails for me, but it works if I remove the line with `applications: [:jose]`, which I suggested.

**Comment by josevalim** [comment]
Me too, that should not make a difference here. :)

**Comment by DesmondLouis** [comment]
@josevalim what else could be the cause of this then

**Comment by josevalim** [comment]
It is hard for me to say if I cannot reproduce it. If you can push a way to reproduce to Github, then I can take a look. Removing `applications: [:jose]` work for me, so i would double check it was indeed removed from your project.

**Comment by DesmondLouis** [comment]
I have even completely removed the jose dependency still have the same errors 
```elixir
defmodule ExFirebaseAuthPlug.MixProject do
  use Mix.Project

  def project do
    [
      app: :ex_firebase_auth_plug,
      version: "0.2.2",
      elixir: "~> 1.14",
      start_permanent: Mix.env() == :prod,
      deps: deps(),
      description: description(),
      package: package(),
      deps: deps(),
      name: "Ex Firebase Elixir API Library",
      source_url: "https://github.com/stagedates/ex_firebase_auth_plug",
      docs: [
        main: "Ex Firebase Elixir API Library",
        #        logo: "",
        extras: ["README.md"]
      ]
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger],
      mod: {ExFirebaseAuthPlug.Application, []},
      applications: []
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      {:joken, "~> 2.6"},
      # {:jose, "~> 1.11"},
      {:plug, "~> 1.15"},
      {:plug_cowboy, "~> 2.0"},
      {:ex_firebase_auth, "~> 0.5.1"},
      {:ex_doc, ">= 0.0.0", runtime: false},
      {:credo, "~> 1.7", only: [:dev, :test], runtime: false},
      {:versioce, "~> 0.2.1"}
    ]
  end

  defp description() do
    "Stagedates firebase authentication library."
  end

  defp package() do
    [
      # This option is only needed when you don't want to use the OTP application name
      name: "ex_firebase_auth_plug",
      organization: "stagedates",
      # These are the default files included in the package
      files: ~w(lib .formatter.exs mix.exs README*),
      licenses: ["Proprietary"],
      links: %{"GitHub" => "https://github.com/stagedates/ex_firebase_auth_plug"}
    ]
  end
end




```

**Comment by josevalim** [comment]
As I said above, you have to remove the whole line.

**Comment by josevalim** [comment]
```
  def application do
    [
      extra_applications: [:logger],
      mod: {ExFirebaseAuthPlug.Application, []}
    ]
  end
