### ISSUE TITLE
Fail to generate docs due to earmark_parser_string_lexer not available

### ISSUE THREAD

**Issue by slashmili** [elixir-lang/ex_doc#1933]
I'm trying to publish the latest changes for my package 
https://github.com/slashmili/ex_syslogger

when I run `mix docs`, it fails creating the docs
```
....
==> ex_syslogger
Compiling 2 files (.ex)
    warning: single-quoted strings represent charlists. Use ~c"" if you indeed want a charlist or use "" instead
    │
 96 │     '#Ref' ++ rest = :erlang.ref_to_list(ref)
    │     ~
    │
    └─ lib/ex_syslogger/json_formatter.ex:96:5

Generated ex_syslogger app
Generating docs...
** (UndefinedFunctionError) function :earmark_parser_string_lexer.string/1 is undefined (module :earmark_parser_string_lexer is not available)
    (earmark_parser 1.4.41) :earmark_parser_string_lexer.string(~c"JsonFormatter is formatter that produces a properly JSON object string where the level, message, node, and metadata are JSON object root properties.")
    (earmark_parser 1.4.41) lib/earmark_parser/helpers/leex_helpers.ex:20: EarmarkParser.Helpers.LeexHelpers.tokenize/2
    (earmark_parser 1.4.41) lib/earmark_parser/helpers/lookahead_helpers.ex:16: EarmarkParser.Helpers.LookaheadHelpers.opens_inline_code/1
    (earmark_parser 1.4.41) lib/earmark_parser/parser.ex:668: EarmarkParser.Parser._inline_or_text?/2
    (earmark_parser 1.4.41) lib/earmark_parser/parser.ex:495: EarmarkParser.Parser._consolidate_para/4
    (earmark_parser 1.4.41) lib/earmark_parser/parser.ex:213: EarmarkParser.Parser._parse/4
    (earmark_parser 1.4.41) lib/earmark_parser/parser.ex:66: EarmarkParser.Parser.lines_to_blocks/3
    (earmark_parser 1.4.41) lib/earmark_parser/parser.ex:59: EarmarkParser.Parser.parse_lines/3
```

is there an issue or I'm doing something wrong 🤔 

I already asked checked with https://github.com/RobertDober/earmark_parser/issues/157 project but no luck so far.

---
my env
```
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1]

Elixir 1.17.1 (compiled with Erlang/OTP 27)
```

**Comment by slashmili** [comment]
if I try to run `mix docs` second time, I get this error: 
```

15:19:40.858 [notice] Application makeup exited: exited in: Makeup.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Makeup.Application.start/2 is undefined (module Makeup.Application is not available)
            (makeup 1.1.2) Makeup.Application.start(:normal, [])
            (kernel 10.0) application_master.erl:295: :application_master.start_it_old/4

15:19:40.864 [notice] Application nimble_parsec exited: :stopped

15:19:40.864 [notice] Application earmark_parser exited: :stopped

15:19:40.864 [notice] Application eex exited: :stopped
** (MatchError) no match of right hand side value: {:error, {:makeup, {:bad_return, {{Makeup.Application, :start, [:normal, []]}, {:EXIT, {:undef, [{Makeup.Application, :start, [:normal, []], []}, {:application_master, :start_it_old, 4, [file: ~c"application_master.erl", line: 295]}]}}}}}}
    (ex_doc 0.34.2) lib/mix/tasks/docs.ex:336: Mix.Tasks.Docs.run/3
    (mix 1.16.1) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.16.1) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /Users/milad/.asdf/installs/elixir/1.16.1-otp-26/bin/mix:2: (file)
```

**Comment by josevalim** [comment]
I sent a PR to your repo that fixes the issue.

**Comment by Shakadak** [comment]
For people that encounter the same problem, what @josevalim did was to update how the applications to be started are specified.  
See https://github.com/slashmili/ex_syslogger/pull/27/files .  
See https://hexdocs.pm/mix/Mix.Tasks.Compile.App.html for more details on what these keys do.
