### ISSUE TITLE
Gulp instructions

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#282]
I am following the instructions in https://github.com/elixir-lang/ex_doc/tree/master/assets
but I cannot get it to work.

i run `gulp` from the ex_doc dir, and i get:

```sh
Error: Cannot find module 'gulp-load-plugins'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/w/git/eksperimental/ex_doc/gulpfile.js:8:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
```

**Comment by eksperimental** [comment]
somehow i mistakenly ran `sudo npm install gulp` and not `sudo npm install`

now when i run `sudo npm install` i get

```
npm WARN unmet dependency /home/eksperimental/ex_doc/node_modules/gulp-minify-css/node_modules/readable-stream,
npm WARN unmet dependency which is version 2.0.2
npm WARN unmet dependency /home/eksperimental/ex_doc/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/eksperimental/ex_doc/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/eksperimental/ex_doc/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/eksperimental/ex_doc/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
```

and when i run `gulp`
```
Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/eksperimental/ex_doc/node_modules/gulp-load-plugins/node_modules/multimatch/node_modules/minimatch/minimatch.js:10:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by Dignifiedquire** [comment]
Sounds like your npm setup is a bit messed up. Try this

```js
$ cd ex_doc
$ rm -rf node_modules
$ npm install
```

You should never user `sudo` for any `npm install` commands, especially not local ones, that will mess up your day

**Comment by Dignifiedquire** [comment]
If you need more help, jump on IRC, that's quicker

**Comment by eksperimental** [comment]
@Dignifiedquire it didnt work. I'm on IRC

**Comment by Dignifiedquire** [comment]
@eksperimental sorry I'm out now..are you around later?

**Comment by eksperimental** [comment]
@Dignifiedquire I may not, but do not worry, whenever I see you on IRC i will talk to you. thanks!

**Comment by eksperimental** [comment]
thank you so much @Dignifiedquire  for all the help!
