### ISSUE TITLE
Tests are failing due to latest changes in Elixir master

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#291]
I think it's related to the latest chagnes related to Behaviour
I haven't followed what were the last changes about, so I cannot fix it.
```
  1) test module_page outputs behavior and callbacks (ExDoc.Formatter.HTML.TemplatesTest)
     test/ex_doc/formatter/html/templates_test.exs:178
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:112: Enumerable.reduce/3
       (elixir) lib/enum.ex:1398: Enum.reduce/3
       (elixir) lib/enum.ex:1047: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:107: ExDoc.Retriever.generate_node/3
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2

....

  2) test module_page outputs the protocol type (ExDoc.Formatter.HTML.TemplatesTest)
     test/ex_doc/formatter/html/templates_test.exs:192
     ** (ExDoc.Retriever.Error) module CustomProtocol is not defined/available
     stacktrace:
       (ex_doc) lib/ex_doc/retriever.ex:65: ExDoc.Retriever.get_module/2
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:49: ExDoc.Retriever.docs_from_modules/2
       test/ex_doc/formatter/html/templates_test.exs:28: ExDoc.Formatter.HTML.TemplatesTest.get_module_page/1
       test/ex_doc/formatter/html/templates_test.exs:193

...

  3) test docs_from_files properly tag implementations (ExDoc.RetrieverTest)
     test/ex_doc/retriever_test.exs:172
     ** (ExDoc.Retriever.Error) module CustomProtocol.Number is not defined/available
     stacktrace:
       (ex_doc) lib/ex_doc/retriever.ex:65: ExDoc.Retriever.get_module/2
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:49: ExDoc.Retriever.docs_from_modules/2
       test/ex_doc/retriever_test.exs:173



  4) test docs_from_files returns the specs for each non-private function (ExDoc.RetrieverTest)
     test/ex_doc/retriever_test.exs:62
     ** (ExDoc.Retriever.Error) module TypesAndSpecs is not defined/available
     stacktrace:
       (ex_doc) lib/ex_doc/retriever.ex:65: ExDoc.Retriever.get_module/2
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:49: ExDoc.Retriever.docs_from_modules/2
       test/ex_doc/retriever_test.exs:63

..

  5) test ignore impl internal functions (ExDoc.RetrieverTest)
     test/ex_doc/retriever_test.exs:177
     ** (ExDoc.Retriever.Error) module CustomProtocol.Number is not defined/available
     stacktrace:
       (ex_doc) lib/ex_doc/retriever.ex:65: ExDoc.Retriever.get_module/2
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:49: ExDoc.Retriever.docs_from_modules/2
       test/ex_doc/retriever_test.exs:178



  6) test undocumented callback implementations get default doc (ExDoc.RetrieverTest)
     test/ex_doc/retriever_test.exs:146
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:112: Enumerable.reduce/3
       (elixir) lib/enum.ex:1398: Enum.reduce/3
       (elixir) lib/enum.ex:1047: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:107: ExDoc.Retriever.generate_node/3
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2



  7) test ignore protocols internal functions (ExDoc.RetrieverTest)
     test/ex_doc/retriever_test.exs:164
     ** (ExDoc.Retriever.Error) module CustomProtocol is not defined/available
     stacktrace:
       (ex_doc) lib/ex_doc/retriever.ex:65: ExDoc.Retriever.get_module/2
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:49: ExDoc.Retriever.docs_from_modules/2
       test/ex_doc/retriever_test.exs:165

.......

  8) test docs_from_files returns the specs for non-private macros (ExDoc.RetrieverTest)
     test/ex_doc/retriever_test.exs:73
     ** (ExDoc.Retriever.Error) module TypesAndSpecs is not defined/available
     stacktrace:
       (ex_doc) lib/ex_doc/retriever.ex:65: ExDoc.Retriever.get_module/2
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:49: ExDoc.Retriever.docs_from_modules/2
       test/ex_doc/retriever_test.exs:74

.

  9) test docs_from_files returns the spec info for each non-private module type (ExDoc.RetrieverTest)
     test/ex_doc/retriever_test.exs:83
     ** (ExDoc.Retriever.Error) module TypesAndSpecs is not defined/available
     stacktrace:
       (ex_doc) lib/ex_doc/retriever.ex:65: ExDoc.Retriever.get_module/2
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:49: ExDoc.Retriever.docs_from_modules/2
       test/ex_doc/retriever_test.exs:84

.

 10) test docs_from_files__properly_tag_protocols (ExDoc.RetrieverTest)
     test/ex_doc/retriever_test.exs:159
     ** (ExDoc.Retriever.Error) module CustomProtocol is not defined/available
     stacktrace:
       (ex_doc) lib/ex_doc/retriever.ex:65: ExDoc.Retriever.get_module/2
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:49: ExDoc.Retriever.docs_from_modules/2
       test/ex_doc/retriever_test.exs:160



 11) test retrieves macro callbacks from behaviours (ExDoc.RetrieverTest)
     test/ex_doc/retriever_test.exs:138
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:112: Enumerable.reduce/3
       (elixir) lib/enum.ex:1398: Enum.reduce/3
       (elixir) lib/enum.ex:1047: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:107: ExDoc.Retriever.generate_node/3
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2

..

 12) test ignore behaviours internal functions (ExDoc.RetrieverTest)
     test/ex_doc/retriever_test.exs:130
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:112: Enumerable.reduce/3
       (elixir) lib/enum.ex:1398: Enum.reduce/3
       (elixir) lib/enum.ex:1047: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:107: ExDoc.Retriever.generate_node/3
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2

.....

 13) test module_page outputs the types and function specs (ExDoc.Formatter.HTML.TemplatesTest)
     test/ex_doc/formatter/html/templates_test.exs:129
     ** (ExDoc.Retriever.Error) module TypesAndSpecs is not defined/available
     stacktrace:
       (ex_doc) lib/ex_doc/retriever.ex:65: ExDoc.Retriever.get_module/2
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:49: ExDoc.Retriever.docs_from_modules/2
       test/ex_doc/formatter/html/templates_test.exs:28: ExDoc.Formatter.HTML.TemplatesTest.get_module_page/1
       test/ex_doc/formatter/html/templates_test.exs:130

......................................

 14) test run generates index.html and normalized options (ExDoc.Formatter.HTMLTest)
     test/ex_doc/formatter/html_test.exs:130
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:112: Enumerable.reduce/3
       (elixir) lib/enum.ex:1398: Enum.reduce/3
       (elixir) lib/enum.ex:1047: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:107: ExDoc.Retriever.generate_node/3
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2



 15) test run generates the html file with the documentation and readme.html (ExDoc.Formatter.HTMLTest)
     test/ex_doc/formatter/html_test.exs:48
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:112: Enumerable.reduce/3
       (elixir) lib/enum.ex:1398: Enum.reduce/3
       (elixir) lib/enum.ex:1047: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:107: ExDoc.Retriever.generate_node/3
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2



 16) test run generates trying to set 'main: index', should fail (ExDoc.Formatter.HTMLTest)
     test/ex_doc/formatter/html_test.exs:140
     Expected exception ArgumentError but got Protocol.UndefinedError (protocol Enumerable not implemented for nil)
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:112: Enumerable.reduce/3
       (elixir) lib/enum.ex:1398: Enum.reduce/3
       (elixir) lib/enum.ex:1047: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:107: ExDoc.Retriever.generate_node/3
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2



 17) test run generates the readme file (ExDoc.Formatter.HTMLTest)
     test/ex_doc/formatter/html_test.exs:96
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:112: Enumerable.reduce/3
       (elixir) lib/enum.ex:1398: Enum.reduce/3
       (elixir) lib/enum.ex:1047: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:107: ExDoc.Retriever.generate_node/3
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2

.

 18) test run generates in specified output directory and redirect index.html file (ExDoc.Formatter.HTMLTest)
     test/ex_doc/formatter/html_test.exs:58
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:112: Enumerable.reduce/3
       (elixir) lib/enum.ex:1398: Enum.reduce/3
       (elixir) lib/enum.ex:1047: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:107: ExDoc.Retriever.generate_node/3
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2



 19) test run should not generate the readme file (ExDoc.Formatter.HTMLTest)
     test/ex_doc/formatter/html_test.exs:106
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:112: Enumerable.reduce/3
       (elixir) lib/enum.ex:1398: Enum.reduce/3
       (elixir) lib/enum.ex:1047: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:107: ExDoc.Retriever.generate_node/3
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2



 20) test run generates the overview file (ExDoc.Formatter.HTMLTest)
     test/ex_doc/formatter/html_test.exs:87
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:112: Enumerable.reduce/3
       (elixir) lib/enum.ex:1398: Enum.reduce/3
       (elixir) lib/enum.ex:1047: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:107: ExDoc.Retriever.generate_node/3
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2



 21) test run generates all listing files (ExDoc.Formatter.HTMLTest)
     test/ex_doc/formatter/html_test.exs:70
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:112: Enumerable.reduce/3
       (elixir) lib/enum.ex:1398: Enum.reduce/3
       (elixir) lib/enum.ex:1047: Enum.map/2
       (ex_doc) lib/ex_doc/retriever.ex:107: ExDoc.Retriever.generate_node/3
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2



Finished in 2.8 seconds (1.5s on load, 1.3s on tests)
91 tests, 21 failures
```

**Comment by josevalim** [comment]
I will investigate. Which elixir version?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Sorry, the version is in the title. I will fix it when I get home. :)

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
I can't reproduce this. :( `mix clean && mix test` still errors for you?

**Comment by milmazz** [comment]
@josevalim @eksperimental In my case all the tests are running OK.

**Comment by eksperimental** [comment]
ok. i think there was something wrong with the compilation from elixir master, 
I recompiled it, and problem solved.
thank you guys, sorry about the false alarm
