### ISSUE TITLE
Error trying to create docs for Ecto

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#294]
I'm getting the following error when I try to generate Ecto's documentation.

```
$ ../ex_doc/bin/ex_doc "Ecto" "0.16" _build/shared/lib/ecto/ebin -m Ecto
** (UndefinedFunctionError) undefined function: :sbroker.module_info/1 (module :sbroker is not available)
    :sbroker.module_info(:attributes)
    lib/ex_doc/retriever.ex:228: ExDoc.Retriever.callbacks_of/1
    lib/ex_doc/retriever.ex:223: anonymous fn/1 in ExDoc.Retriever.callbacks_implemented_by/1
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
    lib/ex_doc/retriever.ex:223: ExDoc.Retriever.callbacks_implemented_by/1
    lib/ex_doc/retriever.ex:92: ExDoc.Retriever.generate_node/3
```

How to reproduce this error:

```
$ cd /tmp
$ git clone https://github.com/elixir-lang/ex_doc && cd ex_doc && mix do deps.get, compile
$ cd ..
$ git clone https://github.com/elixir-lang/ecto && cd ecto && mix do deps.get, compile
$ ../ex_doc/bin/ex_doc "Ecto" "0.16" _build/shared/lib/ecto/ebin -m Ecto
```

**Comment by josevalim** [comment]
You need to use MIX_ENV=docs mix docs. That's because ecto has
dependencies.... So you need to use the mix task that knows how to load
them. The command line is useful mostly for elixir itself, really.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by milmazz** [comment]
@josevalim Thanks for your suggestion. Issue resolved!
