### ISSUE TITLE
Cannot generate docs (Argument Error in ExDoc.Retriever.find_actual_line/3)

### ISSUE THREAD

**Issue by hubertlepicki** [elixir-lang/ex_doc#518]
I'm trying to generate docs for Ecto master.

```
$ MIX_ENV=docs mix docs
** (ArgumentError) argument error
    lib/ex_doc/retriever.ex:316: ExDoc.Retriever.find_actual_line/3
    lib/ex_doc/retriever.ex:225: ExDoc.Retriever.get_callback/5
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    lib/ex_doc/retriever.ex:123: ExDoc.Retriever.generate_node/3
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    lib/ex_doc/retriever.ex:68: ExDoc.Retriever.docs_from_modules/2
    lib/ex_doc.ex:47: ExDoc.generate_docs/3

```

I am not sure if this is an issue with `ex_doc` or `Ecto` itself. My Elixir and Erlang versions:

```
elixir -v
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.2.2
```

Any ideas?

**Comment by josevalim** [comment]
Which ExDoc version?

**Comment by hubertlepicki** [comment]
```
MIX_ENV=docs mix deps | grep ex_doc
* ex_doc 0.11.2 (Hex package) (mix)
  locked at 0.11.2 (ex_doc)
```

0.11.2

**Comment by josevalim** [comment]
`mix deps.update ex_doc` fixes it. :) I will push an updated one to Ecto as well.

**Comment by hubertlepicki** [comment]
True, that helps @josevalim thank you. Possibly requiring 0.11.4 for Ecto makes sense.
