### ISSUE TITLE
Missing version error with Umbrella app

### ISSUE THREAD

**Issue by cloud8421** [elixir-lang/ex_doc#731]
Hello,

I just updated to version `0.16.1` in an umbrella application.

Upon running `mix docs`, this is the error that I get:

```
** (ArgumentError) :version key is required in config, got: [app: nil, aliases: [], build_per_environment: true, build_scm: Mix.SCM.Path, config_path: "config/config.exs", consolidate_protocols: true, default_task: "run", deps_path: "deps", elixirc_paths: ["lib"], erlc_paths: ["src"], erlc_include_path: "include", erlc_options: [:debug_info], lockfile: "mix.lock", preferred_cli_env: [], apps_path: "apps", build_embedded: false, start_permanent: false, deps: [ex_doc: "~> 0.16.1"]]
    lib/mix/tasks/docs.ex:148: Mix.Tasks.Docs.fetch_version!/1
    lib/mix/tasks/docs.ex:125: Mix.Tasks.Docs.run/3
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
```

I've created a minimal example here: <https://github.com/cloud8421/ex_doc_error_example>

It's an umbrella app created with Elixir 1.4.4 and I just added the ex_doc dependency, run `mix deps.get` and `mix docs`.

It looks like a change in behaviour (I see that [this commit](https://github.com/elixir-lang/ex_doc/commit/931c7ee00b8ef517379472ef1b20657bedf23eac) introduces this explicit version check), so I have a couple of questions:

- Should I include `ex_doc` in actual apps in the umbrella instead of the parent?
- Should I specify a version for the umbrella itself (if that's the case, it may be worth updating the umbrella generator for Mix itself)

**Comment by ericmj** [comment]
> Should I specify a version for the umbrella itself

This is a workaround that might work but we should handle it in ex_doc itself.

**Comment by cloud8421** [comment]
Thanks @ericmj I'll use the workaround for now as the umbrella ends up having a version anyway when distillery prepares the release.
