### ISSUE TITLE
Strange error when a struct type contains a `tempN` when is_integer(N) field

### ISSUE THREAD

**Issue by ejpcmac** [elixir-lang/ex_doc#833]
I’m unable to generate the documentation for one of my projects due to a bug. I’ve isolated it into this minimal module:

```elixir
defmodule Measurement do
  @moduledoc """
  Temperature measurement struct.
  """

  defstruct [:timestamp, :temp1]

  @typedoc "A temperature measurement"
  @type t() :: %__MODULE__{
          timestamp: integer(),
          temp1: integer()
        }
end
```

If you add this module to a project and try to generate the documentation with `mix doc`, you should get the following exception:

```
    ** (KeyError) key "p1" not found in: %{"pppppp1" => "<a href=\"https://hexdocs.pm/elixir/typespecs.html#basic-types\">integer</a>", "pppppp2" => "<a href=\"https://hexdocs.pm/elixir/typespecs.html#basic-types\">integer</a>"}
        (stdlib) :maps.get("p1", %{"pppppp1" => "<a href=\"https://hexdocs.pm/elixir/typespecs.html#basic-types\">integer</a>", "pppppp2" => "<a href=\"https://hexdocs.pm/elixir/typespecs.html#basic-types\">integer</a>"})
        (ex_doc) lib/ex_doc/formatter/html/autolink.ex:301: anonymous fn/2 in ExDoc.Formatter.HTML.Autolink.replace_placeholders/2
        (elixir) lib/regex.ex:666: Regex.apply_list/5
        (elixir) lib/regex.ex:661: Regex.apply_list/5
        (elixir) lib/regex.ex:603: Regex.do_replace/4
        (ex_doc) lib/ex_doc/formatter/html/autolink.ex:138: anonymous fn/5 in ExDoc.Formatter.HTML.Autolink.all_typespecs/3
        (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ex_doc) lib/ex_doc/formatter/html/autolink.ex:137: ExDoc.Formatter.HTML.Autolink.all_typespecs/3
```

My few checks converge to the following case: if the type of a struct contains a field named `tempNx` where `N` is an integer, it fails.

**Comment by josevalim** [comment]
ExDoc v0.18.3 released. :)
