### ISSUE TITLE
Impossible to build docs for Earmark

### ISSUE THREAD

**Issue by RobertDober** [elixir-lang/ex_doc#840]
I was not succesfull in finding any trace of this on the net.

As indicated by @pragdave in this issue https://github.com/pragdave/earmark/issues/185
the ex_doc escript fails with the following stacktrace.
```
** (EXIT from #PID<0.68.0>) an exception was raised:
    ** (ArgumentError) argument error
        (ex_doc) lib/ex_doc/formatter/html/autolink.ex:247: anonymous fn/7 in ExDoc.Formatter.HTML.Autolink.format_and_extract_typespec_placeholders/4
        (elixir) lib/macro.ex:257: Macro.do_traverse/4
        (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/macro.ex:243: Macro.do_traverse/4
        (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/macro.ex:243: Macro.do_traverse/4
        (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```
It was launched from Earmark's commit https://github.com/pragdave/earmark/commit/41c84f5f441d2b6201da593447a5790b05551ddd with the following args

`Earmark 1.2.5 _build/dev/lib/earmark/ebin -m Earmark -o doc -p https://github/pragdave/earmark.html -f html -n -n https://hexdocs.pm/earmark/master` 

The env was 1.6.4/20.3

All I could find out was that `elixir_source` is `nil` in line 244, but that code is way over my head.

**Comment by wojtekmach** [comment]
Hi, which ex_doc version are you using? There were bugs in autolink code that were fixed in 0.18.3.

Could you help me reproducing this on the earmark repo? I tried `mix docs` and got an error:

```
~/src/other/earmark[master]% mix docs
** (ErlangError) Erlang error: :enoent
    :erlang.open_port({:spawn_executable, '/Users/wojtek/.mix/escripts/ex_doc'}, [:use_stdio, :exit_status, :binary, :hide, {:args, ["Earmark", "1.2.5", "_build/dev/lib/earmark/ebin", "-m", "Earmark", "-o", "doc", "-p", "https://github/pragdave/earmark.html", "-f", "html", "-n", "-n", "https://hexdocs.pm/earmark/master"]}])
    (elixir) lib/system.ex:634: System.cmd/3
    (mix) lib/mix/task.ex:353: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:277: Mix.Task.run/2
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

**Comment by josevalim** [comment]
@wojtekmach i think it requires the ex_doc script to be installed locally. :)

**Comment by wojtekmach** [comment]
sure, I did that but it still doesn't work.

**Comment by wojtekmach** [comment]
ok, I had ex_doc escript installed in a different directory. I was able to reproduce it, will try to fix it.

**Comment by RobertDober** [comment]
However I am not sure you shall use `ex_doc` inside the Earmark

In case you hit a wall I tell you how we do it

* `mix escript.install hex ex_doc` from the ex_doc repro, Earmark's docs task finds it there
* overrule with EX_DOC_ESCRIPT var as I use asdf

Thank you for your reactivity

**Comment by wojtekmach** [comment]
thanks @RobertDober, I was able to reproduce the bug by building ex_doc's docs :) stay tuned!

**Comment by RobertDober** [comment]
and yes of course we use 0.18.3 so we can probably publish `Earmark 1.2.5` with an older version

0.18.2 same bug, 0.18.1 works.
